### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by pedro-f-nogueira** [pedro-araujo/movienucleobase#12]
We should start a database using SQLite, this will surely be useful in the future and it will make working with gephi easier.

**Comment by pedro-araujo** [comment]
Why SQLite? Why not JSON or XML? Can you list the pros and cons of each one? As far I am aware, it is possible to import data into Gephi in any of the mentioned formats.

Before we proceed, we should first create a proposal for the schema that we are going to use for storing the data into an external format.

The data that we have now is:

- Movie title (string)
- Movie subwikia (string)
- List of scenes (list of strings)
- List of characters (list of MovieCharacter)

For each character we are extracting:
- Name (string)
- Real name (string)
- Gender (string)
- Characters interacted with (Python dictionary with two columns: Name of the character interacted with; How many interactions happened with said character)
- Mentioned characters (Python dictionary with two columns: Name of the mentioned character; How many times the said character was mentioned by the current character)
- Appeared scenes (list of strings)

**Comment by pedro-f-nogueira** [comment]
This question actually got me thinking so i did some research. So I will
point out some arguments to support my choice for using SQLite in this
project.

SQLite > XML or JSON
1. Gephi does no accept XML or JSON  as inputs. (There are other cool tools
to draw social networks but i think Gephi is fills our needs and we already
know how to use it)
2. Performance is better than XML (a)
3. After giving it some thought, transitioning to MySQL after the project
is bigger might be a good idea and SQLite will make this change easier.
4. In my opinion having a database is a better solution for our problem and
will allow easier data manipulation and analysis.
    It offers the means(queries) to access our data in a much easier way.
5. Some other advantages of SQLite. (b)

SQLite > MySQL or PostgreSQL
1. Implementing these two databases just seems to big at this moment. It
might be an option in the future, but not right now.

Why SQLite:
It has a lot of advantages (c), its easy to work with in python (d)

(a)
http://stackoverflow.com/questions/77726/xml-or-sqlite-when-to-drop-xml-for-a-database
(b)https://www.sqlite.org/aff_short.html
(c)https://www.sqlite.org/aff_short.html
(d)
http://sebastianraschka.com/Articles/2014_sqlite_in_python_tutorial.html#initializing

About our database:

I think we should have 4 tables:

movies - Data relevant to the movies
id_m (PK) - Integer- Id
name - Text - Name

chars - Data relevant to the chars
id_m (FK) - Integer - Refers the id of the movie
id_c - Integer - Id
name - Text - Name
real_name - Full name
gender - Text - Gender
n_scenes - Integer - Number of scenes the chars appears
n_scenes_descr - Text - Scenes the char appears separated by commas(ex:
1,2,3,4,..)
n_scenes_mention - Integer - Number of scenes the chars is mentioned
n_scenes_mention_descr - Text - Scenes the char is mentioned separated by
commas(ex: 1,2,3,4,..)

interactions - Data relevant to char interactions / mentions
id_m (FK) - Integer- Id
char_1_id (FK) - Integer (refers id_c)
char_2_id (FK) - Integer (refers id_c)
n_interactions - Integer - Number of times the chars interacted physically
type - Integer - 0 if its and interaction / 1 if its a mention

Note: 
char interaction - If two chars speak in the same scene we assume they are interacting
char mention - If a char speaks of another in a scene we assume that as a mention.
This allows us to evaluate passive characters that might be important to the plot

The separation of interactions and mentions into different tables not only
allows better data manipulation but it is easier to import data to create a
social a network.

So if you don't have any doubts or things to point out i'll move forward
with this part of the project.

2016-01-10 19:18 GMT+00:00 Pedro Araujo notifications@github.com:

**Comment by pedro-f-nogueira** [comment]
Issue resolved.
